### ISSUE TITLE
Create init scripts to add whitelisted users

### ISSUE THREAD

**Issue by geek** [geek/minio-proto#1]
We need to make it easy to preload a list of allowed accounts... we should probably add a script to add individual accounts to the table after the service is running.

Any other sql bootstrapping?

**Comment by cjihrig** [comment]
I don't think there is currently anything else that needs to be bootstrapped. There are only three tables:

- `bridges` - I don't think we would bootstrap any bridges.
- `bridge_usage` - If there are no bridges, there is no usage.
- `accounts` - This is mentioned in the OP.
